# Generated by Django 6.0.7 on 2026-08-16 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ecomm_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('category_slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('category_desc', models.TextField(blank=True, null=True)),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('category_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ecom_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150, unique=True)),
                ('product_slug', models.SlugField(max_length=150, unique=True)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('product_description', models.TextField()),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_quantity_in_stock', models.IntegerField()),
                ('product_is_active', models.BooleanField(default=True)),
                ('product_is_featured', models.BooleanField(default=False)),
                ('product_created_at', models.DateTimeField(auto_now_add=True)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='furnish.ecomm_category')),
            ],
        ),
    ]
