# Generated by Django 6.1 on 2026-08-23 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnish', '0002_ecom_favourites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecom_favourites',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='furnish.ecom_product'),
        ),
    ]
