# Generated by Django 6.1 on 2026-08-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnish', '0005_ecom_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecom_adress',
            name='address_type',
            field=models.TextField(default='Home'),
        ),
    ]
