# Generated by Django 6.1 on 2026-08-28 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furnish', '0006_ecom_adress_address_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecom_adress',
            name='address_type',
        ),
    ]
