# Generated by Django 6.1 on 2026-09-02 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnish', '0007_remove_ecom_adress_address_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ecom_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(choices=[('cod', 'Cash On Delivery'), ('online', 'Online Payment')], default='cod', max_length=20)),
                ('payment_status', models.CharField(choices=[('failed', 'Failed'), ('completed', 'Completed'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('order_tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('order_placed_at', models.DateField(auto_now_add=True)),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='furnish.ecom_adress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ecom_OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='furnish.ecom_order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='furnish.ecom_product')),
            ],
        ),
    ]
