# Generated by Django 6.1 on 2026-09-02 07:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnish', '0008_ecom_order_ecom_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecom_order',
            name='order_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ecom_order',
            name='payment_mode',
            field=models.CharField(choices=[('online', 'Online Payment'), ('cod', 'Cash On Delivery')], default='cod', max_length=20),
        ),
        migrations.AlterField(
            model_name='ecom_order',
            name='payment_status',
            field=models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
