# Generated by Django 6.1 on 2026-09-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnish', '0009_alter_ecom_order_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecom_order',
            name='razor_order_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='ecom_order',
            name='razor_payment_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='ecom_order',
            name='razorpay_signeture',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ecom_order',
            name='payment_mode',
            field=models.CharField(choices=[('cod', 'Cash On Delivery'), ('online', 'Online Payment')], default='cod', max_length=20),
        ),
        migrations.AlterField(
            model_name='ecom_order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
