from django.urls import path
from .views import *

urlpatterns = [
    path('', home_view, name='home'),
    path('home/', home_view, name='home_alt'),
    path('search/', search, name='search'),
    path('search/<str:query>/', search, name='search_with_query'),
    path('aboutus/', aboutus, name='aboutus'),
    path('about/', aboutus, name='about'),
    path('contact/', contact, name='contact'),
    path('products/', products, name='products'),
    path('testimonials/', testimonials, name='testimonials'),
    path('login/', login, name='login'),
    path('register/', register, name='register'),
    path('logout/', logout, name='logout'),
    path('change_password/', change_password, name='change_password'),
    path('product/<slug:pslug>', get_product_detail_view, name='get_product_detail_view'),
    path('category/<slug:cslug>', get_product_from_category, name='get_product_from_category'),
    path('favourites/', view_favourites, name='favourites'),
    path('add-to-favourites/<int:pid>/', add_to_fav, name='add_to_fav'),
    path('add-to-favourites/<int:userId>/<int:pid>/', add_to_fav, name='add_to_fav_alt'),
    path('remove-from-favourites/<int:pid>/', remove_from_fav, name='remove_from_fav'),
    path('cart/', view_cart, name='cart'),
    path('add-to-cart/<int:pid>/', add_to_cart, name='add_to_cart'),
    path('update-cart/<int:pid>/<str:action>/', update_cart_quantity, name='update_cart_quantity'),
    path('remove-from-cart/<int:pid>/', remove_from_cart, name='remove_from_cart'),
    path('manage-address/', manage_address_page, name='manage_address_page'),
    path('add-address/', add_address, name='add_address'),
    path('remove-address/<int:address_id>/', remove_address, name='remove_address'),
    path('checkout/', checkout, name='checkout'),
    path('order-process/', order_process, name='order_process'),
    path('payment/<uuid:order_id>/', payment_page, name='payment_page'),
    path('payment-callback/', payment_callback, name='payment_callback'),
    path('orders/', orders, name='orders'),
    path('ai/chat/', ai_chat_view, name='ai_chat'),
    path('ai/clear/', ai_clear_history_view, name='ai_clear'),
    path('ai/assistant/', ai_assistant_page, name='ai_assistant'),
]

